services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
  
  payment:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn start:dev payments
    env_file:
      - ./apps/payments/.env
    # ports:
    #   - '3003:3003' // exposed over TCP
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn start:dev notifications
    env_file:
      - ./apps/notifications/.env
    # ports:
    #   - '3004:3004' not needed. EXPOSED over TCP
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
